from django.db import models

# Create your models here.
class East(models.Model):
    layoutno = models.TextField()
    bedl = models.FloatField()
    bedw = models.FloatField()
    bedx = models.TextField() 
    bedy = models.TextField()
    kitl = models.FloatField()
    kitw = models.FloatField()
    kitx = models.TextField()  
    kity = models.TextField()
    toil = models.FloatField() 
    toiw = models.FloatField() 
    toix = models.TextField() 
    toiy = models.TextField()
    drawl = models.FloatField()
    draww = models.FloatField() 
    drawx = models.TextField() 
    drawy = models.TextField()
    stal = models.FloatField() 
    staw = models.FloatField() 
    stax = models.TextField() 
    stay = models.TextField()
    dinl = models.FloatField() 
    dinw = models.FloatField() 
    dinx = models.TextField() 
    diny = models.TextField()
    ctoil = models.FloatField() 
    ctoiw = models.FloatField() 
    ctoix = models.TextField() 
    ctoiy = models.TextField()
    stol = models.FloatField() 
    stow = models.FloatField() 
    stox = models.TextField() 
    stoy = models.TextField()
    otsl = models.FloatField() 
    otsw = models.FloatField() 
    otsx = models.TextField() 
    otsy = models.TextField()
    washl = models.FloatField() 
    washw = models.FloatField() 
    washx = models.TextField() 
    washy = models.TextField()
    entl = models.FloatField() 
    entw = models.FloatField() 
    entx = models.TextField() 
    enty = models.TextField()
    parl = models.FloatField() 
    parw = models.FloatField() 
    parx = models.TextField() 
    pary = models.TextField()
    garl = models.FloatField() 
    garw = models.FloatField() 
    garx = models.TextField() 
    gary = models.TextField()
    foyl = models.FloatField() 
    foyw = models.FloatField() 
    foyx = models.TextField() 
    foyy = models.TextField()
    util = models.FloatField() 
    utiw = models.FloatField() 
    utix = models.TextField() 
    utiy = models.TextField()

    def __str__(self):
        return self.layoutno






