# Generated by Django 3.0.5 on 2020-07-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0002_auto_20200725_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='east',
            name='id',
        ),
        migrations.AlterField(
            model_name='east',
            name='layoutno',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
