# Generated by Django 3.0.5 on 2020-07-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbar', '0003_auto_20200725_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='east',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='east',
            name='layoutno',
            field=models.TextField(),
        ),
    ]
